# Generated by Django 5.1.1 on 2024-11-09 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioWeb', '0002_usuario_billetera'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
