# Generated by Django 5.1.1 on 2024-11-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioWeb', '0003_producto_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logos/')),
            ],
            options={
                'verbose_name': 'Configuracion del logo',
                'verbose_name_plural': 'Configuracion del logo',
                'db_table': 'Logo',
            },
        ),
    ]
