# Generated by Django 5.1.1 on 2024-11-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioWeb', '0004_configuracionlogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionlogo',
            name='nombre',
            field=models.CharField(default='Logo', max_length=255),
        ),
    ]
