# Generated by Django 5.1.1 on 2024-11-15 22:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioWeb', '0005_configuracionlogo_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionlogo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
