# Generated by Django 5.1.1 on 2024-11-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioWeb', '0007_personalizarcolores'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComisionAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_acumulado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Comisión Administrador',
                'verbose_name_plural': 'Comisiones Administrador',
                'db_table': 'ComisionAdmin',
            },
        ),
    ]
