# Generated by Django 5.1.1 on 2024-11-29 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitioWeb', '0008_comisionadmin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comisionadmin',
            options={'verbose_name': 'Comisión ', 'verbose_name_plural': 'Comision '},
        ),
    ]
